name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  IS_BEHIND_NAT: true
  RUST_LOG: debug
  IPGEOLOCATIONIO_API_KEY: ${{ secrets.IPGEOLOCATIONIO_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install resolvconf wireguard wireguard-tools
    - name: Set up WireGuard
      run: |
        echo "[Interface]" >> /etc/wireguard/wg0.conf
        echo "PrivateKey = ${{ secrets.WG_IFACE_PRIVATE_KEY }}" >> /etc/wireguard/wg0.conf
        echo "Address = ${{ secrets.WG_IFACE_ADDRESS }}" >> /etc/wireguard/wg0.conf
        echo "DNS = 1.1.1.1" >> /etc/wireguard/wg0.conf
        echo "[Peer]" >> /etc/wireguard/wg0.conf
        echo "PublicKey = ${{ secrets.WG_PEER_PUBLIC_KEY }}" >> /etc/wireguard/wg0.conf
        echo "Endpoint = ${{ secrets.WG_PEER_ENDPOINT }}" >> /etc/wireguard/wg0.conf
        echo "AllowedIPs = ${{ secrets.WG_PEER_ENDPOINT }}" >> /etc/wireguard/wg0.conf
        sudo wg-quick up wg0
    - name: Run ip addr
      run: ip addr
    - name: Run cat ipv6
      run: cat /sys/module/ipv6/parameters/disable
    - name: Run sysctl
      run: sysctl -a 2>/dev/null | grep disable_ipv6
    - name: Run curl
      run: curl icanhazip.com
    - name: Run ping6
      run: curl -6 icanhazip.com
