name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  IS_BEHIND_NAT: true
  RUST_LOG: debug
  IPGEOLOCATIONIO_API_KEY: ${{ secrets.IPGEOLOCATIONIO_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Set up WireGuard
      uses: egor-tensin/setup-wireguard@v1
      with:
        endpoint: '${{ secrets.WG_PEER_ENDPOINT }}'
        endpoint_public_key: '${{ secrets.WG_PEER_PUBLIC_KEY }}'
        ips: '${{ secrets.WG_IFACE_ADDRESS }}'
        allowed_ips: '${{ secrets.WG_PEER_ALLOWED_IPS }}'
        private_key: '${{ secrets.WG_IFACE_PRIVATE_KEY }}'
    - name: Run
      run: cargo run
